#!/usr/bin/python -tt
# -*- coding:utf-8 -*-

import random
from twython import Twython
from auth import (
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)

twitter = Twython(
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)

messages = [
        "its a goodnight in the ghetto",
        "get rich or die tryin",
        "420-666=69",
        "its lit",
        "carrot cake!",
        "oh yeah baby",
        "pick up the phone",
        "yeah i smoke newports",
        "!!!",
        "lets go hawaii!!!",
        "mind blown",
        "ive done things ive never dreamed off,good and bad.",
        "get real weird",
        "ive entered the matrix",
        "hack the planet!",
        "i should listen more",
        "you never really know",
        "666",
        "fuck fox news",
        "smoke yourself fools",
        "have you ever gotten real high off love??",
        "the real me",
        "just playing,i the real miss me",
        "i miss you",
        "777 lucky",
        "the internet is cool",
        "smoke it fools",
        "oh the things ive done",
        "get real or keep it fake",
        "lit romney",
        "a tweet from my Rasberry Pi",
        "chillary clinton",
        "Random tweet showing my disgust for android",
        "Lifes a trip,dont fall #deep",
        "RIP Mac Dre",
        "VAMOS SACRAMENTO REPUBLIC",
        "#AFCB",
        "#AFCB 4 LIFE",
        "Ohh yea, you gotta get schwifty. ",
        "insert @fatmankey lyric here",
        "tell me your favorite moment?",
        "been about this life",
        "atleast im gonna be at the next world cup",
        "i really miss Meddilin",
        "BOURNEMOUTH",
        "GO CHERRIES #AFCB",
        "you havent lived until you have been to Carnival",
        "ive seen the entire country but always end back in california",
        "something_tight.jpg",
        "shutdown",
        "my sleep is so out of whack",
        "neo from the matrix had the sickest phone",
        "tight tight tight tight tight tight",
        "fav for something tight",
        "this heat",
        "leveled up",
        "next level",
        "thank you if you have ever taken care of me faded.",
        "do you,just dont get me in trouble",
        "oh shit thats tight.",
        "you been lockedup?",
        "whats your favorite hot pocket?",
        "tastino's > digiorno",
        "go gurt it my man",
        "gatorade is my jam",
        "where you been at?",
        "<3",
        "i smoke fools like you on the b-ball court",
        "i got homies in atlanta",
        "i got homies in cleveland",
        "i got homies in the bay",
        "skepta.",
        "newports baby",
        "time to get next level wasted",
        "unreal tourny 2k3",
        "fifa?",
         "rip mac dre",
         "i really go dumb in my backpack",
         "party pack",
         "what you talking bout keef like that for?",
         "love for the game",
         "love for the streets",
         "off the beats by eileen",
         "less than local bby",
         "skateboarding causes blindess",
         "make america skate again",
         "jaws needs a rain coat",
         "this game is seasoned like a tasty steak",
         "i got my colombian shorties",
         "aye girls the DM be open",
         "damn im a nerd",
         "C R E S T",
         "quitting smoking is rough",
         "i love baseball,soccer and a nice scotch",
        
        
       ]
message = random.choice(messages)

twitter.update_status(status=message)

